--- qq	2013-06-25 12:05:15.000000000 +0700
+++ Makefile	2013-09-05 12:52:41.325399608 +0700
@@ -5,7 +5,7 @@
 #TARGET		:= 2.6.33.5
 KERNEL_MODULES	:= /lib/modules/$(TARGET)
 # KERNEL_BUILD	:= $(KERNEL_MODULES)/build
-KERNEL_BUILD	:= /usr/src/linux-headers-$(TARGET)
+KERNEL_BUILD	:= /usr/src/linux-$(TARGET)
 
 #SYSTEM_MAP	:= $(KERNEL_BUILD)/System.map
 SYSTEM_MAP	:= /boot/System.map-$(TARGET)
